### PR TITLE
fix(Interaction): prevent controller swap breaking use functionality - resolves #343

### LINKED ISSUE #343: Using items doesn't work as expected when the object is swapped between hands
If you pick up an object in one hand and start using it, then without releasing the use button on that controller, grab the item with the other controller

It will continue to be used until the button on the original controller is released,

Upon ungrab, the force stop using on the controller should also be called.

### PR DESCRIPTION
**Pull request by thestonefox**
Previously, when using an object and swapping controllers (either
grab or touch state) the use state on the object would not be reset
correctly and therefore the previous using controller would still
be considered the active use controller.

This fix ensures that when a controller stops touching or grabbing
an object, that the use state on the controller is also reset to
no longer using the object.

### CODE REVIEW

**Comment by thestonefox** [comment]
resolves #335

**Comment by thestonefox** [comment]
fixes #335

**Comment by thestonefox** [comment]
fixes #335

**Comment by thestonefox** [comment]
resolves #343

File: Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractUse.cs [hunk 1]
```diff
@@ -57,6 +57,14 @@ public void ForceStopUsing()
             }
         }
 
+        public void ForceResetUsing()
```
Comment (thestonefox) [inline Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractUse.cs]: need to add docs for this method
